version: '3.4'

services:
  payservice.api:
    image: ${DOCKER_REGISTRY-}payserviceapi
    networks:
      - app-net
    build:
      context: .
      dockerfile: src/PayService.API/Dockerfile
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-net
    restart:
      always

networks:
  app-net:
    driver: bridge